name: Check Dependabot Alerts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for Dependabot alerts
        uses: your-username/check-dependabot-alerts@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
